[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'honza/vim-snippets'
on_i = 1

[[plugins]]
repo = 'vim-scripts/sudo.vim'
on_i = 1

[[plugins]]
repo = 'sjl/gundo.vim'
on_i = 1

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]] # check syntax
repo = 'scrooloose/syntastic'
on_i = 1

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1

[[plugins]] # JavaScript libraries highlight
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
